version: 2.1
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Mew World"
    steps:
      - run: echo << parameters.to >>
  
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - sayhello:
        to: "Omar"
      - run: echodsadas Hello, Bye!
      - run: echo HELLO ERROR!!
        when: on_fail
  say-bye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello

